### PR TITLE
[BUGFIX release] relationship [x, y] should not break on x.unloadRecord()

### LINKED ISSUE #4986: unloadRecord of child record causes hasMany relationship to be invalid using ember-data@2.13
## Example repo and integration test to reproduce the issue
- [ember-data 2.13.1 (broken)](https://github.com/sudowork/unloadrecord-ember-data-bug/tree/ember-data213)
- [ember-data 2.12.2 (working)](https://github.com/sudowork/unloadrecord-ember-data-bug/tree/ember-data212)

_Update_: I wrote a test case to test this behavior https://github.com/sudowork/data/commit/89a34ba7b59535bc679e8b6f7ea7108cc13fbf45. I bisected the issue to have started with 6d96eda226f15738b23032bc25c009e081070359 (from #4593).

_Update 2_: Converted the repo I had to an ember-twiddle now that I can load 2.13: [https://ember-twiddle.com/df7fa30d2eb3d32efe16185f4f376128?openFiles=controllers.todo-list.js%2C](ember-twiddle)

## Steps to reproduce:

```javascript
// models/todo-list.js
import DS from 'ember-data';
import { hasMany } from 'ember-data/relationships';

export default DS.Model.extend({
  todos: hasMany('todo', { async: false }),
});
```

1. Assume you have a model `todo-list` which `hasMany` `todo` items as `todos` already loaded in the store and is currently in scope.
1. Call [`todos.removeObject(todo)`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR29) to remove the item from the relationship
1. Call [`this.store.unloadRecord(todo)`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR31) to clean up the record from the store
1. Explicitly try accessing [`get(this, 'model.todos')`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR34) again to load the `todo` records. (Expected result: `[]`, Actual result: Assertion error thrown).

The assertion error thrown is due to [this assertion](https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-private/system/relationships/state/has-many.js#L244) that checks that `manyArray.isEvery('isEmpty', false)` on `[null]`.

### 2.13.1 (broken)

unloadrecord213

### 2.12.2 (working)

unloadrecord212

Note: On 2.12, it does not even go through `getRecords()` when retrieving the records again.

### PR DESCRIPTION
**Pull request by stefanpenner**
For an async relationship [x, y] with x.unloadRecord(), now adjusts only the relationship’s currentState, leaving that relationship’s canonical state alone, ensuring the existing client-side delete semantics are preserved. But when that relationship is reloaded, the canonicalState consulted.

For sync relationship [x, y] with x.unloadRecord(), both currentState and canonical state are updated. This is to mirror the client-side delete semantics. But since we cannot reload a sync relationship we must assume this to be the new canonical state and rely on subsequent `push` or `adapterPayloads` or manual `store.push` to update.

This aims to:

* [FIX] hasMany arrays never contain dematerialized records (so they no longer become broken)
* [FIX] using unloadRecord as a type of client side delete
* [PRESERVE] the garbage collector pass to cleanup orphaned models
* [PRESERVE] second access to a relationship which did contain an unloadRecord to cause a reload

note: if both sides of a relationships are unloaded, the above doesn’t apply. This is largely just when members of a loaded relationship are themselves unloaded.

[fixes #4986 #5052 #4987 #4996]

### CODE REVIEW

**Comment by stefanpenner** [comment]
@sudowork I have included your failing test (to ensure this does address the issue)

**Comment by stefanpenner** [comment]
@workmanw I'm not sure if this also addresses https://github.com/emberjs/data/issues/5025 it may not, as that sounds like its in the land of record array manager. If you can provide a failing test, I can take a look.

File: tests/integration/relationships/has-many-test.js [hunk 1]
```diff
@@ -1645,6 +1727,37 @@ testInDebug('A sync hasMany errors out if there are unlaoded records in it', fun
   }, /You looked up the 'comments' relationship on a 'post' with id 1 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async \('DS.hasMany\({ async: true }\)'\)/);
 });
 
+testInDebug('After removing and unloading a record, a hasMany relationship should still be valid', function(assert) {
```
Comment (hjdivad) [inline tests/integration/relationships/has-many-test.js]: why `testInDebug` vs `test`?

File: tests/unit/model/relationships/has-many-test.js [hunk 2]
```diff
@@ -1383,6 +1383,71 @@ test('deleting an item that is the current state of a belongsTo clears currentSt
...
+
+  let person = env.store.peekRecord('person', 1);
+  let cars = person.get('cars');
+
+  assert.equal(cars.get('length'), 2);
+
+  run(() => {
+    cars.get('firstObject').unloadRecord();
+    // assert.equal(cars.get('length'), 1); // unload now..
+    // assert.equal(person.get('cars.length'), 1); // unload now..
```
Comment (hjdivad) [inline tests/unit/model/relationships/has-many-test.js]: dead code

File: tests/unit/model/relationships/has-many-test.js [hunk 3]
```diff
@@ -1747,16 +1812,19 @@ test('DS.hasMany proxy is destroyed', function(assert) {
...
-  let people = tag.get('people');
+  let peopleProxy = tag.get('people');
 
-  return people.then(() => {
+  return peopleProxy.then(people => {
     Ember.run(() => {
       tag.unloadRecord();
-      assert.equal(people.get('isDestroying'), true);
-      assert.equal(people.get('isDestroyed'),  false);
+      assert.equal(people.isDestroying, false, 'people is destroying sync after unloadRecord');
```
Comment (hjdivad) [inline tests/unit/model/relationships/has-many-test.js]: assertion msg inverted

File: tests/unit/model/relationships/has-many-test.js [hunk 4]
```diff
@@ -1747,16 +1812,19 @@ test('DS.hasMany proxy is destroyed', function(assert) {
...
+      assert.equal(people.isDestroyed, false, 'people is NOT YET destroyed sync after unloadRecord');
+      assert.equal(peopleProxy.isDestroying, false, 'peopleProxy is destroying sync after unloadRecord');
```
Comment (hjdivad) [inline tests/unit/model/relationships/has-many-test.js]: assertion msg inverted

File: tests/unit/model/relationships/has-many-test.js [hunk 5]
```diff
@@ -1383,6 +1383,71 @@ test('deleting an item that is the current state of a belongsTo clears currentSt
...
+
+  assert.equal(cars.get('length'), 2);
+
+  run(() => {
+    cars.get('firstObject').unloadRecord();
+    // assert.equal(cars.get('length'), 1); // unload now..
+    // assert.equal(person.get('cars.length'), 1); // unload now..
+  });
+
+  // assert.equal(cars.get('length'), 1); // unload now..
```
Comment (hjdivad) [inline tests/unit/model/relationships/has-many-test.js]: dead code

**Comment by rwjblue** [comment]
👍 - This seems like a good path forward to me...
