### PR TITLE
Remove conditional statement that is always true

### LINKED ISSUE #3629: likely broken code due to refactoring
this `if` will always be true, i suspect some meaning existed in the past but now something seems sideways.

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest-adapter.js#L818

### PR DESCRIPTION
**Pull request by bmac**
Closes #3629

### CODE REVIEW

File: packages/ember-data/lib/adapters/rest-adapter.js [hunk 1]
```diff
@@ -815,15 +815,12 @@ export default Adapter.extend(BuildURLMixin, {
...
-            jqXHR.status,
-            parseResponseHeaders(jqXHR.getAllResponseHeaders()),
-            response || payload
-          );
-        }
+
+        let response = adapter.handleResponse(
+          jqXHR.status,
+          parseResponseHeaders(jqXHR.getAllResponseHeaders()),
+          response || payload
```
Comment (tchak) [inline packages/ember-data/lib/adapters/rest-adapter.js]: `response || payload` -> `payload`

**Comment by tchak** [comment]
@bmac LGTM except for the little adjustment I made in the comments

File: packages/ember-data/lib/adapters/rest-adapter.js (hunk 1 above)
Comment (stefanpenner) [inline packages/ember-data/lib/adapters/rest-adapter.js]: :+1:
