### PR TITLE
[BUGFIX beta] [fixes #4509] createRecord initializes correctly

### LINKED ISSUE #4509: `init` event fires before leaving empty state
Consider the following model definition:

``` javascript
import Model from "ember-data/model";
import attr from "ember-data/attr";
import { belongsTo, hasMany } from "ember-data/relationships";
import Ember from 'ember';

export default Model.extend({
  title: attr(),
  propSetFromObservingTitle: attr(),

  setPropFromTitle: Ember.observer('title', function() {
      this.set('propSetFromObservingTitle', this.get('title') + 'hi');
  }).on('init')
});
```

In this example, we have two properties that are `DS.attr`'s. We have `propSetFromObservingTitle` because we basically want a computed property that _also_ gets serialized to the server.

This code works with normal ember objects, but when we run the following code:

``` javascript
this.store.createRecord('post', {title: 'foo'});
```

We get the following exception:

```
VM423 ember.debug.js:31321 Error: Attempted to handle event `didSetProperty` on <post:null> while in state root.empty. Called with {name: propSetFromObservingTitle, oldValue: undefined, originalValue: undefined, value: undefinedhi}.
    at new Error (native)
    at Error.EmberError (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:15976:21)
    at InternalModel._unhandledEvent (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.7.0/ember-data.js:2623:13)
    at InternalModel.send (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.7.0/ember-data.js:2501:14)
    at Class.set (https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.7.0/ember-data.js:13361:31)
    at Descriptor.computedPropertySet [as _set] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:14654:28)
    at Descriptor.computedPropertySetWithSuspend [as setWithSuspend] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:14634:19)
    at Descriptor.computedPropertySetEntry [as set] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:14612:17)
    at Object.set (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:20348:12)
    at Class.set (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.6.2/ember.debug.js:34672:38)
```

Example on Ember Twiddle: https://ember-twiddle.com/415538f55bbaa01ca95067ec0e890d43?openFiles=models.post.js%2C

### PR DESCRIPTION
**Pull request by stefanpenner**
* by the name Model.prototype.init is called, internal model’s data has been loaded
* do no emit extra change events during `createRecord` as the attributes are the initial state.

### CODE REVIEW

**Comment by fivetanley** [comment]
Awesome! 👍

File: addon/-private/system/store.js [hunk 1]
```diff
@@ -365,16 +365,8 @@ Store = Service.extend({
...
-    let record = internalModel.getRecord();
-
-    // Move the record out of its initial `empty` state into
-    // the `loaded` state.
-    // TODO @runspired this seems really bad, store should not be changing the state
     internalModel.loadedData();
-
-    // Set the properties specified on the record.
-    // TODO @runspired this is probably why we do the bad thing above
-    record.setProperties(properties);
```
Comment (runspired) [inline addon/-private/system/store.js]: yay! I like to see my TODOs removed validly :D

**Comment by stefanpenner** [comment]
@bmac do you want to handle the backport to beta or should I?
