### PR TITLE
[bugfix beta] Fetch cancels unload

### LINKED ISSUE #5343: model.unloadRecord causes Uncaught TypeError: Cannot read property 'eachAttribute' of null
```
at new Snapshot (-private.js:5069)
    at InternalModel.createSnapshot (-private.js:6894)
    at Class._flushPendingFetchForType (-private.js:10771)
    at cb (ember-metal.js:5546)
    at OrderedSet.forEach (ember-metal.js:5358)
    at MapWithDefault.forEach (ember-metal.js:5554)
    at Class.flushAllPendingFetches (-private.js:10687)
    at invoke (backburner.js:258)
    at Queue.flush (backburner.js:151)
```
This is after calling `findRecord` `then` `unloadRecord` on the result. We are upgrading to ember 2.18 and ember-data 2.18, and this appears to be a regression.

Twiddle reproduction:
https://ember-twiddle.com/c16533267ff13353b25498fac4d05ca3?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

Possibly a duplicate of https://github.com/emberjs/data/issues/4963, but that was supposedly fixed a while ago.

The code that doesn't work is this:
```
this.get('store').findRecord('person', 1).then((person) => {
   person.unloadRecord();
});
```

### PR DESCRIPTION
**Pull request by hjdivad**
When fetching records, cancel internal model destruction if it is
scheduled, ie if the model is dematerializing because it was unloaded.

It is not possible to construct snapshots for dematerializing internal
models.  Prior to this commit, this could happen when fetching a record
in the same runloop that it was unloaded.  A straightfoward way of
getting into this state was via

```
store.findRecord('book', 1).then(b => b.unloadRecord())
```

when the model is already cached in the store.  Under these conditions,
the fetch is scheduled, then the promise fulfills with the cached record
and is unloaded and *then* the scheduled fetch is flushed.

[fix #5343]

### CODE REVIEW

File: addon/-private/system/store.js [hunk 1]
```diff
@@ -921,6 +925,9 @@ Store = Service.extend({
       // will once again convert the records to snapshots for adapter.findMany()
       let snapshots = new Array(totalItems);
       for (let i = 0; i < totalItems; i++) {
+        if (internalModels[i].hasScheduledDestroy()) {
+          internalModels[i].cancelDestroy();
```
Comment (igorT) [inline addon/-private/system/store.js]: Why are we canceling in two places? Does the test catch both instances where canceling is required?

**Comment by sly7-7** [comment]
I tested the scenario in which I reproduced #5343, and this seems to work. Thanks a lot @hjdivad

File: addon/-private/system/store.js (hunk 1 above)
Comment (hjdivad) [reply addon/-private/system/store.js]: per OOB discussion, moving all cancelation to flush

**Comment by sly7-7** [comment]
@bmac A very kindlyi-smoothy-loving ping to ship a new beta... 😺

**Comment by bmac** [comment]
@sly7-7 I just published [v3.1.0-beta.2](https://github.com/emberjs/data/releases/tag/v3.1.0-beta.2).

**Comment by sly7-7** [comment]
Thank you So much @bmac

**Comment by phantomphildius** [comment]
@bmac thank you this also fixes the same issue we were having!

**Comment by jaswilli** [comment]
I just tested this on a `2.18.2` app and it fixes it there as well. Any chance of `2.18.3` bugfix release? 😄

**Comment by aalasolutions** [comment]
Please release 2.18.4 ember data with this fix. 2.18 is still in LTS branch and we need this fix

**Comment by rwjblue** [comment]
@aalasolutions - FWIW, there have not been _any_ ember-data versions that are LTS. The only project that has released any LTS versions to date has been Ember itself (ember-source npm package).

**Comment by aalasolutions** [comment]
@rwjblue hmm, right. meanwhile I have totally ditched unloadRecord and in my component, i filtered the records which are not required. So I guess I can live with that for now

**Comment by bmac** [comment]
I just cherry-picked this commit to the 2.18 branch and release Ember Data 2.18.4.

(Sorry @rwjblue I should have pinged you to give you a heads up first).
