### PR TITLE
Don't notify relationships with links during initialization

### LINKED ISSUE #4942: hasMany association with links causes backtracking re-render error
Running against Canary I'm getting the following error when a has many relationship with links is used in a template:

```
Assertion Failed: You modified "meeting.attendees" twice on <minutebase@model:meeting::ember1351:772c5e6e-aceb-11e6-ae79-770161ca087d> in a single render. It was rendered in "component:mb-pages/dashboard/meeting" and modified in "component:mb-pages/dashboard/meeting". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
Error
    at assert (http://minutebase.dev:4202/assets/vendor.js:21770:13)
    at assert (http://minutebase.dev:4202/assets/vendor.js:33521:34)
    at Object.assertNotRendered (http://minutebase.dev:4202/assets/vendor.js:39296:11)
    at Object.propertyDidChange (http://minutebase.dev:4202/assets/vendor.js:37912:30)
    at Class.propertyDidChange (http://minutebase.dev:4202/assets/vendor.js:51064:19)
    at Class.notifyPropertyChange (http://minutebase.dev:4202/assets/vendor.js:51078:12)
    at InternalModel.notifyPropertyChange (http://minutebase.dev:4202/assets/vendor.js:140423:21)
    at ManyRelationship.updateLink (http://minutebase.dev:4202/assets/vendor.js:147451:19)
    at ManyRelationship.push (http://minutebase.dev:4202/assets/vendor.js:147529:16)
    at Relationships.get (http://minutebase.dev:4202/assets/vendor.js:146885:24)
```

Looks like `updateLink` is notifying property change and causing Glimmer to re-evaluate the relationship and so it explodes.

I narrowed it down to when #4821 was merged, which makes sense as I assume that the links was previously resolved in advance but not happens when it's accessed.

Here's a [twiddle](https://ember-twiddle.com/e9ddeefbf25aea4fa2c27d9fe8e5fd01?openFiles=mirage.config.js%2C) which will hopefully demonstrate it, I can't get it working against ember-data canary as I get an error of "No application initializer named 'store'"

### LINKED ISSUE #5017: ember-data 2.14.0: Assertion Failed: You modified "model.players" twice on ... in a single render.
Just updating `ember-data` to `2.14.0` from `2.13.1` I have this following error.

**NodeJs** 7.10.0 - **npm** 5.0.3

```
Assertion Failed: You modified "model.players" twice on <myapp@model:team::ember767:1> in a single render. It was rendered in "template:myapp/templates/team.hbs" and modified in "template:myapp/templates/team.hbs". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
Error
    at assert (http://localhost:4200/assets/vendor.js:18622:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:18835:34)
    at http://localhost:4200/assets/vendor.js:35859:27
    at runInDebug (http://localhost:4200/assets/vendor.js:18735:5)
    at Object.runInDebug (http://localhost:4200/assets/vendor.js:18859:38)
    at Object.assertNotRendered (http://localhost:4200/assets/vendor.js:35833:23)
    at Object.propertyDidChange (http://localhost:4200/assets/vendor.js:34476:30)
    at Class.propertyDidChange (http://localhost:4200/assets/vendor.js:47793:19)
    at Class.notifyPropertyChange (http://localhost:4200/assets/vendor.js:47807:12)
    at InternalModel.notifyPropertyChange (http://localhost:4200/assets/vendor.js:79047:20)
defaultDispatch @ ember.debug.js:19818
dispatchError @ ember.debug.js:19797
invokeWithOnError @ ember.debug.js:2200
flush @ ember.debug.js:2256
flush @ ember.debug.js:2380
end @ ember.debug.js:2450
(anonymous) @ ember.debug.js:3016
```

My **package.json**:

```
"broccoli-asset-rev": "^2.5.0",
"ember-ajax": "^3.0.0",
"ember-cli": "2.13.2",
"ember-cli-app-version": "^3.0.0",
"ember-cli-babel": "^6.4.1",
"ember-cli-babili": "^0.2.0",
"ember-cli-code-coverage": "^0.3.12",
"ember-cli-dependency-checker": "^2.0.0",
"ember-cli-deploy": "^1.0.1",
"ember-cli-eslint": "^3.1.0",
"ember-cli-htmlbars": "^2.0.2",
"ember-cli-htmlbars-inline-precompile": "^0.4.3",
"ember-cli-inject-live-reload": "^1.6.1",
"ember-cli-qunit": "^4.0.0",
"ember-cli-sass": "^6.2.0",
"ember-cli-shims": "^1.1.0",
"ember-cli-sri": "^2.1.1",
"ember-data": "2.14.0",
"ember-export-application-global": "^2.0.0",
"ember-load-initializers": "^1.0.0",
"ember-resolver": "^4.1.0",
"ember-responsive": "^2.0.4",
"ember-simple-auth": "^1.3.0",
"ember-source": "~2.13.3",
"loader.js": "^4.5.0",
"run-sequence": "~1.2.2"
```

**team.hbs**:
```
{{#each model.players key="id" as |player index|}}
  <a href="[somerUrl]" class="{{player.statusClass}}">
    <span>{{player.code}}</span>
    {{#if player.isOk}}
      {{#each player.fighters.content as |fighter|}}
        <div class="fighter {{fighter.fighterClass}}">{{fighter.fighterText}}</div>
      {{/each}}
    {{/if}}
  </a>
  {{else}}
  {{#if model.players.isPending}}
    Loading...
  {{else}}
    Nothing to show.
  {{/if}}
{{/each}}
```

**Why this error?**

### LINKED ISSUE #5023: 2.14.0: included relationship in JSONAPISerializer with additional links.related causes backtracking re-render
Demo app here: https://github.com/buschtoens/ember-data-included-records-demo  
Ember Data 2.13 works fine.

When a JSONAPI compliant server responds with included relationships, but also includes a `links.related` field, Ember crashes with a [backtracking re-render error](https://github.com/emberjs/ember.js/issues/13948), if that relationship was accessed in a template.

```js
{
  "data": {
    "type": "authors",
    "id": "1",
    "attributes": {
      "age": 20,
      "last-name": "Corkery",
      "first-name": "Joseph"
    },
    "relationships": {
      "blog-posts": {
        "data": [
          {
            "type": "blog-posts",
            "id": "1"
          },
          {
            "type": "blog-posts",
            "id": "2"
          }
        ],
        "links": {
          "related": "/show-stopper" // <=== this is the culprit
        }
      }
    }
  },
  "included": [
    {
      "type": "blog-posts",
      "id": "1",
      "attributes": {
        "text": "Enim et nihil. Nihil optio voluptas blanditiis. Officiis dignissimos consequatur eum. Et et eveniet sapiente voluptas soluta optio est.",
        "title": "aut odit voluptas"
      },
      "relationships": {
        "author": {
          "data": {
            "type": "authors",
            "id": "1"
          }
        }
      }
    },
    {
      "type": "blog-posts",
      "id": "2",
      "attributes": {
        "text": "Dolores ab consequatur exercitationem. Alias nisi quod sint animi iusto doloremque blanditiis. Enim accusantium animi et officia.",
        "title": "unde et aut"
      },
      "relationships": {
        "author": {
          "data": {
            "type": "authors",
            "id": "1"
          }
        }
      }
    }
  ]
}
```

A request to `/show-stopper` is never actually performed.

### PR DESCRIPTION
**Pull request by mmun**
Fixes #4942.
Fixes #5023.
Fixes #5017.

I also took to the liberty of changing https://github.com/emberjs/data/compare/bugfix/4942?expand=1#diff-fd4c34d9a34dfde73cd3413128a3c973L2876 to be more explicit.

If this change is approved, we should reach out to people linking to this issue after a release is cut.
- [ ] https://github.com/travis-ci/travis-web/pull/1173
- [ ] https://github.com/acquia/ember-drupal-waterwheel/issues/6
- [ ] https://github.com/niklaslong/ember-has-many/commit/28708aaf88a2cc452f0b4546746456c2c097290b
- [ ] https://github.com/emberobserver/client/commit/7f4c39c30a8f80e9a4b75c964bb4e2c272e030fc
- [ ] https://github.com/fossasia/open-event-frontend/pull/399
- [ ] https://github.com/emberjs/ember.js/issues/13948#issuecomment-314464308
- [ ] https://github.com/rust-lang/crates.io/pull/893

### CODE REVIEW

File: addon/-private/system/relationships/state/relationship.js [hunk 1]
```diff
@@ -346,7 +346,7 @@ export default class Relationship {
     this.store._updateRelationshipState(this);
   }
 
-  updateLink(link) {
+  updateLink(link, initial) {
```
Comment (runspired) [inline addon/-private/system/relationships/state/relationship.js]: where is this `true` ?

Comment (mmun) [inline addon/-private/system/relationships/state/relationship.js]: https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/create.js#L72

Furthermore, this line and the one in my PR are the _only_ places that call `Relationship#push` in the test suite.

Comment (runspired) [inline addon/-private/system/relationships/state/relationship.js]: oooooh, that this arg was already present implies that at some point we'd thought of this case and lost it

**Comment by fivetanley** [comment]
@mmun maybe it's possible for people to try it out using github links in their package.json?

**Comment by fivetanley** [comment]
definitely belongs in a release but i wonder if we can get additional feedback before this is merged (not a blocker just an idea)

**Comment by mmun** [comment]
@fivetanley I agree! I tried it out on someone's example app and it fixed the bug: https://github.com/emberjs/data/issues/5023#issuecomment-321414113. I'd still like if other users could confirm this fix works for them.

If someone would like to try it out in their app, just change your ember-data dependency to

```
"ember-data": "emberjs/data#bugfix/4942",
```

**Comment by tsteuwer** [comment]
Will try in the morning on our apps.

**Comment by stefanpenner** [comment]
Fix looks good. But we will need a test or two

**Comment by mmun** [comment]
Hmm... I'm not sure of the right way to test this. The problematic assertion is very coupled to rendering so I guess we can write a regression test via a component integration test.

**Comment by rtablada** [comment]
@mmun if you want to pair a bit on testing it, I've got some time tomorrow and I'm definitely interested in getting more involved in the E-D side of things.

**Comment by aureliosaraiva** [comment]
@mmun Very nice! 

I tested my applications and solved the problem.

**Comment by stefanpenner** [comment]
@mmun there is an observable difference re: change notifications, so a isolated test with some strategically placed listeners (cp dk's or ovservers) should do the trick in isolation, outside of rendering.

**Comment by mmun** [comment]
@stefanpenner Hmm for some reason I thought there wouldn't be but I'll try that first.

**Comment by mmun** [comment]
Tests added. I confirmed that they fail before the fix is applied.

**Comment by stefanpenner** [comment]
> BTW, should I label this for [BUGFIX release]?

👍

**Comment by stefanpenner** [comment]
* beta backport PR: https://github.com/emberjs/data/pull/5120
* release backport PR: https://github.com/emberjs/data/pull/5121

**Comment by rlivsey** [comment]
Just checked my app against master and can confirm this fixes the issues I was seeing in #4942

Awesome stuff, thank you everyone!

**Comment by buschtoens** [comment]
Thank you *so much*! This was blocking our upgrades for weeks. ♥️

**Comment by bmac** [comment]
I've released [v2.14.10](https://github.com/emberjs/data/releases/tag/v2.14.10) and [v2.15.0-beta.4](https://github.com/emberjs/data/releases/tag/v2.15.0-beta.4) with this bugfix.

**Comment by stefanpenner** [comment]
@mmun thanks for the fix, @bmac thanks for cutting the release.
