### PR TITLE
Free up `internalModel`s

### LINKED ISSUE #3296: Unload issue with relationships
It is not clear what unloading should do with regards to relationships. It seems to me that it should dematerialize a record, but keep the internalModel intact if it has SSOT foreign key references(removing foreign keys seems obviously incorrect).
This is problematic though, because internalModels will still leak memory. How do we let users unload a bunch of related records? Does this mean we have to write a mini Garbage Collector, that will anytime you unload a record, check the foreign key dependencies and unload things it can. This doesn't sound too bad, can you confirm it is the right thing to do?

### PR DESCRIPTION
**Pull request by hjdivad**
`internalModel`s need to stay around as long as they're connected to a live record via relationships.  Once an entire subgraph is removed however, we can free all of it.

Also add a couple of "late private" fields to `internalModel`'s constructor for shape preservation.

Includes work from @igort and @sly7-7

[Fix #3296]
[Supercede #3301]

### CODE REVIEW

File: addon/-private/system/model/states.js [hunk 1]
```diff
@@ -676,8 +676,10 @@ const RootState = {
 
       setup(internalModel) {
         internalModel.clearRelationships();
-        var store = internalModel.store;
-        store._dematerializeRecord(internalModel);
+        // var store = internalModel.store;
+        // store._dematerializeRecord(internalModel);
+
+        // TODO: internalModel.dematerializeRecord() ?
```
Comment (hjdivad) [inline addon/-private/system/model/states.js]: @igort do we actually want to dematerialize on `deleted.saved`?  seems suspect

**Comment by hjdivad** [comment]
cc @stefanpenner @pangratz @igorT @sly7-7

File: addon/-private/system/model/internal-model.js [hunk 2]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+    if (allUnloaded) {
+      relatedInternalModels.forEach((internalModel) => {
+        if (!internalModel.isDestroyed) {
+          internalModel.destroy();
+        }
+      });
+    }
+  },
+
+  destroy: function() {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: concise function

File: addon/-private/system/model/internal-model.js [hunk 3]
```diff
@@ -324,6 +383,7 @@ InternalModel.prototype = {
     @private
   */
   pushedData() {
+    this._isDestroyed = false;
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: this revives internalModels ?

File: addon/-private/system/model/model.js [hunk 4]
```diff
@@ -803,9 +803,9 @@ var Model = Ember.Object.extend(Ember.Evented, {
   willDestroy() {
     //TODO Move!
     this._super(...arguments);
-    this._internalModel.clearRelationships();
-    this._internalModel.recordObjectWillDestroy();
-    //TODO should we set internalModel to null here?
+
+    this._internalModel._resetRecord();
```
Comment (stefanpenner) [inline addon/-private/system/model/model.js]: is there a point to resetting the internal model here, doesn't it just  "go dead" once destroyed?

File: tests/integration/adapter/find-all-test.js [hunk 5]
```diff
@@ -19,6 +19,7 @@ module("integration/adapter/find_all - Finding All Records of a Type", {
       firstName: attr('string'),
       lastName: attr('string')
     });
+    Person.reopenClass({ toString: () => 'Person' });
```
Comment (stefanpenner) [inline tests/integration/adapter/find-all-test.js]: concise function.

File: tests/integration/records/unload-test.js [hunk 6]
```diff
@@ -17,16 +17,25 @@ var Person = DS.Model.extend({
   name: attr('string'),
   cars: hasMany('car', { async: false })
 });
+Person.reopenClass({
+  toString: () => 'Person'
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: ^

File: tests/integration/records/unload-test.js [hunk 7]
```diff
@@ -17,16 +17,25 @@ var Person = DS.Model.extend({
...
+});
 
 var Group = DS.Model.extend({
   people: hasMany('person', { async: false })
 });
+Group.reopenClass({
+  toString: () => 'Group'
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: ^

File: tests/integration/records/unload-test.js [hunk 8]
```diff
@@ -17,16 +17,25 @@ var Person = DS.Model.extend({
...
+});
 
 var Car = DS.Model.extend({
   make: attr('string'),
   model: attr('string'),
   person: belongsTo('person', { async: false })
 });
+Car.reopenClass({
+  toString: () => 'Car'
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: ^

File: tests/integration/records/unload-test.js [hunk 9]
```diff
@@ -280,55 +289,108 @@ test("unloading a record also clears its relationship", function(assert) {
         person.unloadRecord();
       });
 
-      assert.equal(person.get('cars.length'), undefined);
+      assert.expectAssertion(function () {
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: =>

File: tests/integration/records/unload-test.js [hunk 10]
```diff
@@ -280,55 +289,108 @@ test("unloading a record also clears its relationship", function(assert) {
...
   });
-});
-
-test("unloading a record also clears the implicit inverse relationships", function(assert) {
-  var adam, bob;
-  // disable background reloading so we do not re-create the relationship.
-  env.adapter.shouldBackgroundReloadRecord = () => false;
 
-  run(function() {
+  run(function () {
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: =>

File: tests/integration/records/unload-test.js [hunk 11]
```diff
@@ -280,55 +289,108 @@ test("unloading a record also clears its relationship", function(assert) {
...
   });
 
-  run(function() {
-    env.store.findRecord('group', 1).then(function(group) {
-      assert.equal(group.get('people.length'), 1, 'The inital length of people is correct');
-      var person = env.store.peekRecord('person', 1);
-      run(function() {
-        person.unloadRecord();
-      });
+  run(function () {
```
Comment (stefanpenner) [inline tests/integration/records/unload-test.js]: =>

File: addon/-private/system/model/internal-model.js [hunk 12]
```diff
@@ -184,6 +182,14 @@ InternalModel.prototype = {
     this.record = null;
   },
 
+  dematerializeRecord() {
+    if (this.record) {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: when do we call dematerializeRecord and there is no record?

File: addon/-private/system/model/internal-model.js [hunk 13]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
     return this.record;
   },
 
-  unloadRecord() {
+  directlyRelatedInternalModels() {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: brief doc explaining why this method exists.

File: addon/-private/system/model/internal-model.js [hunk 14]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+    var array = [];
+    this.type.eachRelationship((key, relationship) => {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: we may want to use `eachRelationshipByName` cp here: https://github.com/emberjs/data/blob/c9d8212c857ca78218ad98d11621819b38dba98f/addon/-private/system/relationships/ext.js#L486 because it is cached (eachRelBy Name can be costly), and seems like its provides what we want here.

File: addon/-private/system/model/internal-model.js [hunk 15]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+    let array = [];
+    let queue = [];
+    let seen = [];
+    queue.push(this);
+    seen.push(this);
+    while (queue.length > 0) {
+      let node = queue.shift();
+      array.push(node);
+      let related = node.directlyRelatedInternalModels();
+      related.forEach(function(internalModel) {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: =>

File: addon/-private/system/model/internal-model.js [hunk 16]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+        if (seen.indexOf(internalModel) === -1) {
+          queue.push(internalModel);
+          seen.push(internalModel);
+        }
+      });
+    }
+    return array;
+  },
+
+  unloadRecord: function() {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: concise function

File: addon/-private/system/model/internal-model.js [hunk 17]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
     return this.record;
   },
 
-  unloadRecord() {
+  directlyRelatedInternalModels() {
+    var array = [];
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: let?

File: addon/-private/system/model/internal-model.js [hunk 18]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+    var record;
+    for (var i=0; i < relatedInternalModels.length; i++) {
+      record = relatedInternalModels[i].record;
+      if (record && !(record.get('isDestroyed') || record.get('isDestroying'))) {
+        allUnloaded = false;
+        break;
+      }
+    }
+    if (allUnloaded) {
+      relatedInternalModels.forEach((internalModel) => {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: why for loop on 281, but forEach here

File: addon/-private/system/model/internal-model.js [hunk 19]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+        if (!internalModel.isDestroyed) {
+          internalModel.destroy();
+        }
+      });
+    }
+  },
+
+  destroy: function() {
+    this._isDestroyed = true;
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: we should likely mimic embers flags:

* `isDestroying = true` during distruction
* `isDestroyed = true` once destroyed

File: addon/-private/system/model/internal-model.js [hunk 20]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
     return this.record;
   },
 
-  unloadRecord() {
+  directlyRelatedInternalModels() {
+    var array = [];
+    this.type.eachRelationship((key, relationship) => {
+      if (this._relationships.has(key)) {
+        var related = this._relationships.get(key).members.toArray();
+        array.push(...related);
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: this may be fine, but there is an upper limit (in the low hundreds of thousands) that one can push onto an array.

File: addon/-private/system/model/model.js (hunk 4 above)
Comment (igorT) [inline addon/-private/system/model/model.js]: No, the internal model lives on, the record goes dead

File: addon/-private/system/model/internal-model.js (hunk 14 above)
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: we should benchmark

File: addon/-private/system/model/internal-model.js [hunk 21]
```diff
@@ -584,6 +644,15 @@ InternalModel.prototype = {
     });
   },
 
+  _resetRecord() {
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: Can you put a comment saying that this doesn't reset relationships/attributes on purpose, given that constraint, the name is a bit unfortunate

File: addon/-private/system/store.js [hunk 22]
```diff
@@ -794,6 +794,7 @@ Store = Service.extend({
 
     var resolver = Ember.RSVP.defer('Fetching ' + typeClass + 'with id: ' + internalModel.id);
     var pendingFetchItem = {
+      // TODO: s/record/internalModel
```
Comment (igorT) [inline addon/-private/system/store.js]: TODO

File: addon/-private/system/store.js [hunk 23]
```diff
@@ -2430,12 +2430,14 @@ Store = Service.extend({
     @param {InternalModel} internalModel
   */
   _dematerializeRecord(internalModel) {
```
Comment (igorT) [inline addon/-private/system/store.js]: Maybe move to the `internalModel`

File: tests/integration/records/unload-test.js [hunk 24]
```diff
@@ -280,55 +289,108 @@ test("unloading a record also clears its relationship", function(assert) {
...
 
-  run(function() {
+  var rematerializedPerson = bob.get('person');
+  assert.equal(rematerializedPerson.get('.id'), '1');
+  // the person is rematerialized; the previous person is *not* re-used
+  assert.notEqual(rematerializedPerson, adam);
+});
+
+
+test('unloading a disconnected subgraph clears the relevant internal models', function(assert) {
```
Comment (igorT) [inline tests/integration/records/unload-test.js]: Maybe a test for unloading a part of a connected graph doesn't do that?

File: tests/unit/store/unload-test.js [hunk 25]
```diff
@@ -47,7 +49,7 @@ testInDebug("unload a dirty record asserts", function(assert) {
       }
     });
 
-    store.findRecord('record', 1).then(function(record) {
+    store.findRecord('record', 1, { backgroundReload: false }).then(function(record) {
```
Comment (pangratz) [inline tests/unit/store/unload-test.js]: The `store.findRecord` is unnecessary for this test. Let's use `store.peekRecord` instead.

File: tests/unit/store/unload-test.js [hunk 26]
```diff
@@ -157,18 +158,23 @@ test("can commit store after unload record with relationships", function(assert)
 
     asyncRecords = Ember.RSVP.hash({
       brand: store.findRecord('brand', 1),
-      product: store.findRecord('product', 1)
+      product: store.findRecord('product', 1, { backgroundReload: false })
```
Comment (pangratz) [inline tests/unit/store/unload-test.js]: `store.peekRecord`

File: tests/unit/store/unload-test.js [hunk 27]
```diff
@@ -157,18 +158,23 @@ test("can commit store after unload record with relationships", function(assert)
...
       records.like = like.save();
       return Ember.RSVP.hash(records);
     }).then(function(records) {
       store.unloadRecord(records.product);
+    });
+  });
+
+  run(function () {
+    promise.then(function () {
       return store.findRecord('product', 1);
```
Comment (pangratz) [inline tests/unit/store/unload-test.js]: `store.peekRecord`

File: addon/-private/system/model/internal-model.js [hunk 28]
```diff
@@ -95,20 +95,18 @@ export default function InternalModel(type, id, store, _, data) {
   this.store = store;
   this._data = data || new EmptyObject();
   this.modelName = type.modelName;
-  this.dataHasInitialized = false;
+  this._loadingPromise = null;
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: Seems unused?

File: addon/-private/system/model/states.js (hunk 1 above)
Comment (hjdivad) [inline addon/-private/system/model/states.js]: per our discussion offline we'll unload the record (which will dematerialize)

File: addon/-private/system/model/internal-model.js (hunk 17 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: addon/-private/system/model/internal-model.js (hunk 13 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: also this should be `_private`

File: addon/-private/system/model/internal-model.js (hunk 15 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: addon/-private/system/model/internal-model.js (hunk 16 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: addon/-private/system/model/internal-model.js (hunk 18 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: because of `break`

File: addon/-private/system/model/internal-model.js (hunk 2 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: tests/integration/adapter/find-all-test.js (hunk 5 above)
Comment (hjdivad) [inline tests/integration/adapter/find-all-test.js]: 👍

File: tests/integration/records/unload-test.js (hunk 6 above)
Comment (hjdivad) [inline tests/integration/records/unload-test.js]: 👍

File: tests/integration/records/unload-test.js (hunk 7 above)
Comment (hjdivad) [inline tests/integration/records/unload-test.js]: 👍

File: tests/integration/records/unload-test.js (hunk 8 above)
Comment (hjdivad) [inline tests/integration/records/unload-test.js]: 👍

File: tests/integration/records/unload-test.js (hunk 9 above)
Comment (hjdivad) [inline tests/integration/records/unload-test.js]: 👍

File: addon/-private/system/model/internal-model.js (hunk 21 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: i'll put in a comment, but even so, can you suggest a better name?

File: addon/-private/system/model/internal-model.js (hunk 28 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: it is written to elsewhere;   i have added it here to preserve shape.

Really though we should add a setter and not have other parts of the system write private fields

File: addon/-private/system/model/internal-model.js [hunk 29]
```diff
@@ -235,8 +241,68 @@ InternalModel.prototype = {
...
+    }
+  },
+
+  destroy: function() {
+    this._isDestroyed = true;
+    Ember.run.schedule('destroy', this, this.willDestroy, this);
+  },
+
+  willDestroy() {
+    Ember.assert("Cannot destroy an internalModel while its record is materialized", !this.record);
```
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: tests/integration/adapter/find-all-test.js (hunk 5 above)
Comment (pangratz) [inline tests/integration/adapter/find-all-test.js]: I am curious why this is needed. Which tests are failing without this changes? I would guess only tests wich check for assertions, right? Maybe we should only specify the `toString` in those tests...

**Comment by wecc** [comment]
I think this issue would close #4126

**Comment by hjdivad** [comment]
> I think this issue would close #4126 

yes it should

**Comment by hjdivad** [comment]
appveyor build is complaining about downloading phantom.  Just need someone to restart.

@pangratz this should resolve your concerns
@igort this should resolve your concerns except for deleting implicitly unloading: we should do this in a separate effort.

@stefanpenner this should resolve your concerns except for `eachRelationship` vs `eachRelationshipByName`.  That shouldn't block the PR; we can switch it after doing some benchmarks

**Comment by bmac** [comment]
This looks good to me. 👍 

@hjdivad I think @igorT is the only one who can restart an AppVeyor build. So in the past we've been comfortable merged prs when AppVeyor is red and travis is green, if the reason for the AppVeyor failure has to do with a network error during install and there aren't any build changes in the pr.

File: addon/-private/system/model/internal-model.js [hunk 30]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
     return this.record;
   }
 
+
+  /**
+    Computes the set of internal models reachable from `this` acrosxactly one
+    relationship.
+
+    @return {Array} An array containing the internal models that `t` belongs
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: ``` s/`t`/`this`/ ```?

File: addon/-private/system/model/internal-model.js [hunk 31]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
     return this.record;
   }
 
+
+  /**
+    Computes the set of internal models reachable from `this` acrosxactly one
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: acrosxactly?

File: addon/-private/system/model/internal-model.js [hunk 32]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+
+
+  /**
+    Computes the set of internal models reachable from this internaodel.
+
+    Reachability is determind over the relatinoship graph (ie a grawhere
+    nodes are internal models and edges are belongs to or has many
+    relationships.
+
+    @return {Array} An array including `this` and all internal modereachable
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: modereachable

File: addon/-private/system/model/internal-model.js [hunk 33]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+      }
+    });
+    return array;
+  }
+
+
+  /**
+    Computes the set of internal models reachable from this internaodel.
+
+    Reachability is determind over the relatinoship graph (ie a grawhere
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: typo: determind . relatinoship, grawhere

File: addon/-private/system/model/internal-model.js [hunk 34]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+          array.push(related[i]);
+        }
+      }
+    });
+    return array;
+  }
+
+
+  /**
+    Computes the set of internal models reachable from this internaodel.
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: internaodel

File: addon/-private/system/model/internal-model.js [hunk 35]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+          internalModel._bfsId = bfsId;
+        }
+      }
+    }
+    return array;
+  }
+
+
+  /**
+    Unload the record for this internal model.  This will cause thecord to be
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: thecord

File: addon/-private/system/model/internal-model.js [hunk 36]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+    destroyed and freed up for garbage collection.  It will also trer a check
```
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: trer

File: addon/-private/system/model/internal-model.js (hunk 30 above)
Comment (pangratz) [inline addon/-private/system/model/internal-model.js]: Also https://github.com/hjdivad/data/pull/2

**Comment by hjdivad** [comment]
@bmac turns out I can also restart an AppVeyor build by writing comments with such atrocious spelling that @pangratz has to save me with a new commit.

File: addon/-private/system/model/internal-model.js [hunk 37]
```diff
@@ -111,28 +123,28 @@ export default class InternalModel {
...
     // caches for lazy getters
     this.__deferredTriggers = null;
     this._references = null;
     this._recordReference = null;
-    this.__inFlightAttributes = null;
     this.__relationships = null;
-    this.__attributes = null;
     this.__implicitRelationships = null;
+
+    // Used for coloring during BFS
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: should likely explain just a-bit more. BFS doesn't help us understand why/where this is used. Likely would be enough to say "during marking phase of unloading"

File: addon/-private/system/model/internal-model.js [hunk 38]
```diff
@@ -278,8 +290,22 @@ export default class InternalModel {
     this._triggerDeferredTriggers();
   }
 
-  recordObjectWillDestroy() {
+  resetRecord() {
     this.record = null;
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: is there actual value in reseting the record during destroy, or can we just let it go dead.

File: addon/-private/system/model/internal-model.js [hunk 39]
```diff
@@ -278,8 +290,22 @@ export default class InternalModel {
...
+    this.dataHasInitialized = false;
+    this.isReloading = false;
+    this.error = null;
+    this.currentState = RootState.empty;
+    this.__attributes = null;
+    this.__inFlightAttributes = null;
+  }
+
+  dematerializeRecord() {
+    if (this.record) {
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: Curious, should we assert in development if we attempt to dematerialize something already dematerialized? Wouldn't it mean we are doing duplicate work?

File: addon/-private/system/model/internal-model.js [hunk 40]
```diff
@@ -333,14 +359,102 @@ export default class InternalModel {
...
+    relationship.
+
+    @return {Array} An array containing the internal models that `this` belongs
+    to or has many.
+  */
+  _directlyRelatedInternalModels() {
+    let array = [];
+    this.type.eachRelationship((key, relationship) => {
+      if (this._relationships.has(key)) {
+        let related = this._relationships.get(key).members.toArray();
```
Comment (stefanpenner) [inline addon/-private/system/model/internal-model.js]: should we create this array, to just iterate then throw it away?

File: addon/-private/system/model/internal-model.js (hunk 37 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: 👍

File: addon/-private/system/model/internal-model.js (hunk 39 above)
Comment (hjdivad) [inline addon/-private/system/model/internal-model.js]: The case where we wind up here with `!this.record` is `store.unloadAll(type)` which is public API.

We could change this to assert `!!this.record` and then tweak the store to only unload materialized internal models.  thoughts?

**Comment by bmac** [comment]
@hjdivad do you mind rebasing this pr?

**Comment by bmac** [comment]
ping @hjdivad

**Comment by runspired** [comment]
ping @hjdivad, if you don't have time (as I suspect you don't, hi office budy! 👋 ) just say so and I'll pull down your work and try to move it along.

**Comment by trumb1mj** [comment]
Any updates on this?  I'm running into just this problem.  Is there any brute force method to get by this until it has been fixed?

**Comment by hjdivad** [comment]
@runspired @bmac gonna try to get to it this weekend

@runspired i'll likely need to sync up with you re your recent changes in this area

**Comment by runspired** [comment]
@hjdivad I may have to come also crash at your place :P 

@trumb1mj I don't think you are hitting this issue exactly but a different retention issue that's related.

That said, our intention is to make it so that internal models ARE kept if a relationship still has access to them, while your need is explicitly for them to be unloaded even when one does. David @igorT and myself will need to consider this case.

**Comment by trumb1mj** [comment]
@runspired is there any way to build my relationships to avoid this?  

Also, I don't understand why deleting an object with a many-to-1 would cause any residual references to be left around--the other way makes a bit of sense but I still think we should be able to opt out and just whack things.  Not disagreeing just not quite understanding.

File: addon/-private/system/model/internal-model.js [hunk 41]
```diff
@@ -113,26 +124,29 @@ export default class InternalModel {
     this.store = store;
     this._data = data || new EmptyObject();
     this.modelName = modelName;
-    this.dataHasInitialized = false;
     this._loadingPromise = null;
     this._record = null;
-    this.currentState = RootState.empty;
-    this.isReloading = false;
+    // TODO: see if we can clean this up
+    this._isDestroying = false;
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: Either way lets leave a comment on why/how it's used

File: addon/-private/system/model/internal-model.js [hunk 42]
```diff
@@ -113,26 +124,29 @@ export default class InternalModel {
...
     this._isDestroyed = false;
     this.isError = false;
-    this.error = null;
     this._isUpdatingRecordArrays = false;
+    this._isDematerializing = false;
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: Same here

File: addon/-private/system/model/internal-model.js [hunk 43]
```diff
@@ -275,8 +289,9 @@ export default class InternalModel {
     return this._record;
   }
 
+  // TODO: fix the wat of 'get record' and 'getRecord'
   getRecord() {
-    if (!this._record) {
+    if (!this._record && !this._isDematerializing) {
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: We should comment this

File: addon/-private/system/model/internal-model.js [hunk 44]
```diff
@@ -307,8 +322,25 @@ export default class InternalModel {
...
-  recordObjectWillDestroy() {
+  resetRecord() {
+    // TODO: get laziness working again?
     this._record = null;
+    this.dataHasInitialized = false;
+    this.isReloading = false;
+    this.error = null;
+    this.currentState = RootState.empty;
+    this.__attributes = null;
+    this.__inFlightAttributes = null;
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: should we clear out data?

File: addon/-private/system/model/internal-model.js [hunk 45]
```diff
@@ -356,14 +388,109 @@ export default class InternalModel {
...
+    while (queue.length > 0) {
+      let node = queue.shift();
+      array.push(node);
+      let related = node._directlyRelatedInternalModels();
+      for (let i=0; i<related.length; ++i) {
+        let internalModel = related[i];
+        if (internalModel._bfsId < bfsId) {
+          queue.push(internalModel);
+          internalModel._bfsId = bfsId;
+        }
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: would it be worth adding a dev assert if we ever see a case of `internalModel._bfsId > bfsId` ? That would mean bad things are happening

File: addon/-private/system/model/internal-model.js [hunk 46]
```diff
@@ -356,14 +388,109 @@ export default class InternalModel {
...
+    once all models that refer to it via some relationship are also unloaded.
+  */
   unloadRecord() {
     this.send('unloadRecord');
+    this.dematerializeRecord();
+    Ember.run.schedule('destroy', this, '_cleanupOrphanedInternalModels');
+  }
+
+  _cleanupOrphanedInternalModels() {
+    this._isDematerializing = false;
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: Should comment on why we do this here

File: addon/-private/system/model/internal-model.js [hunk 47]
```diff
@@ -356,14 +388,109 @@ export default class InternalModel {
...
+  destroy() {
+    this._isDestroying = true;
+    Ember.run.schedule('destroy', this, this.willDestroy, this);
+  }
+
+  willDestroy() {
+    assert("Cannot destroy an internalModel while its record materialized", !this.record || this.record.get('isDestroyed') || this.record.get('isDestroying'));
+
+    this.store._removeFromIdMap(this);
+    this._isDestroyed = true;
```
Comment (igorT) [inline addon/-private/system/model/internal-model.js]: Should we set isDestroying to false?

Comment (igorT) [inline addon/-private/system/model/internal-model.js]: If we still need it

File: addon/-private/system/model/model.js [hunk 48]
```diff
@@ -808,11 +808,8 @@ const Model = Ember.Object.extend(Ember.Evented, {
   },
 
   willDestroy() {
-    //TODO Move!
     this._super(...arguments);
-    this._internalModel.clearRelationships();
-    this._internalModel.recordObjectWillDestroy();
-    //TODO should we set internalModel to null here?
+    this._internalModel.resetRecord();
```
Comment (igorT) [inline addon/-private/system/model/model.js]: Seems odd to call this from the record into the internalModel. Can we move it somewhere else?

**Comment by Kerrick** [comment]
Did this seem to leave anybody else with severe performance problems?

In previous versions of Ember Data it was relatively quick to `store.unloadAll('my-model-type')` when I had ~2500 of them loaded, but in Ember Data 2.12 it takes upwards of 25 seconds. (In case it's relevant, my model has 5 `hasMany` relationships, and 3 `belongsTo` relationships.)

image


image

**Comment by stefanpenner** [comment]
@kerrick can you open a fresh issue and provide a reproduction. Sounds like something we should look into and that will make this actionable

**Comment by tylerturdenpants** [comment]
@Kerrick I'm also experiencing exactly the same issue. 2.12 was super fast. 2.13-2.15 is so slow at unloading the records that it seems to hang the browser. I've also noticed given certain relationships lead to a memory leak that quickly grows to the gigabyte range of memory in a minute or two and then crashes.
