### PR TITLE
Trap exceptions that are thrown from adapter methods and reject the

### LINKED ISSUE #4945: Throwing in `serialize`
If I throw an error whilst serializing, I was expecting to be able to catch this with `save().catch(...)`

Does this seem reasonable?

https://ember-twiddle.com/e63e22ec26ced2171e2c53cc088af37c?openFiles=controllers.application.js%2C

### PR DESCRIPTION
**Pull request by bmac**
store promise with the exception.

Closes #4945

cc @runspired

### CODE REVIEW

File: tests/integration/store-test.js [hunk 1]
```diff
@@ -913,4 +913,70 @@ testInDebug('store#queryRecord should assert when normalized payload of adapter
...
+  };
+
+  run(() => {
+    store.findRecord('car', 1).catch(error => {
+      assert.equal(error.message, 'Refusing to find record')
+    })
+  });
+});
 
+test('The store should trap exceptions that are thrown from adapter#findRecord', function(assert) {
```
Comment (bmac) [inline tests/integration/store-test.js]: I need to update this test name to reference `findAll`.

**Comment by amk221** [comment]
Hey what's the status on this?
