### PR TITLE
[FIX] only include version in ember-data output

### LINKED ISSUE #6219: `shouldRollupPrivate: false` produces a broken build
I realize this may not be public API, but the `shouldRollupPrivate` flag that now exists in `@ember-data/-build-infra` doesn't appear to work.

The problem is that if you set it to `false`, you get a build that lacks the `version.js` file.

### PR DESCRIPTION
**Pull request by runspired**
Previously we were adding version to the tree in every package (whoops!)

This also ensures that version is always included in the output regardless of whether shouldRollupPrivate is used.

Resolves #6219

### CODE REVIEW

File: packages/-build-infra/src/addon-build-config-for-data-package.js [hunk 1]
```diff
@@ -111,6 +110,9 @@ function addonBuildConfigForDataPackage(PackageName) {
     },
 
     treeForAddon(tree) {
+      if (typeof this._additionalAddonFiles === 'function') {
```
Comment (rwjblue) [inline packages/-build-infra/src/addon-build-config-for-data-package.js]: If this is only needed by `ember-data` package, can we put a custom `treeForAddon` there instead and merge in the file after calling the original implementation here?

Comment (runspired) [reply packages/-build-infra/src/addon-build-config-for-data-package.js]: since we don't have class based inheritance, no :(

Comment (rwjblue) [reply packages/-build-infra/src/addon-build-config-for-data-package.js]: We can definitely do it

```js
module.exports = Object.assign(addonBaseConfig, {
 // other stuff here

  treeForAddon() {
    let tree = addonBaseConfig.treeForAddon.apply(this, arguments);
    return merge([tree,version()]);
  }
});
```

Comment (runspired) [reply packages/-build-infra/src/addon-build-config-for-data-package.js]: 👍
