### PR TITLE
[BUGFIX release] Fix unconsistent behavior in Model.changedAttributes

### LINKED ISSUE #3579: model.changedAttributes() behaves inconsistently
I've observed that `DS.Model.changedAttributes()` behaves differently on new records than on saved ones (the behaviour on the saved models looks correct to me, the one in the new records seems as bug)

If you create a new record and change some of its attributes, `model.changedAttributes()` will return an object with the properties that have changed and the current and previous value, and `model.isDirty` is true. So far so good.

But when you save it, while the request is pending and the record is still being saved, on the new record the changed attributes is cleared (an empty object), while on the already saved record it the changed attributes don't change until the save operation completes.

The behaviour of the saved records seems the right one. The dirty attributes should remain dirty until we get confirmation from the API).

In both cases the record's `isDirty` property is true, is just the `changedAttributes()` function the one that returns the wrong value.

Reproducible live example: http://development.dummy-app.divshot.io/ember-data-dirty-bug
Code: https://github.com/cibernox/dummy-app-for-benchmark

Also I'm curious about why `changedAttributes` is a function and not a computedProperty.

### PR DESCRIPTION
**Pull request by cibernox**
closes #3579

### CODE REVIEW

File: packages/ember-data/lib/system/model/model.js [hunk 1]
```diff
@@ -611,7 +613,9 @@ var Model = Ember.Object.extend(Ember.Evented, {
   */
   changedAttributes: function() {
     var oldData = get(this._internalModel, '_data');
-    var newData = get(this._internalModel, '_attributes');
+    var currentData = get(this._internalModel, '_attributes');
```
Comment (cibernox) [inline packages/ember-data/lib/system/model/model.js]: BTW, I wonder why here we have to use `get` instead of just `this._internalModel._whatever`

File: packages/ember-data/tests/unit/model-test.js [hunk 2]
```diff
@@ -298,6 +297,68 @@ test("changedAttributes() return correct values", function() {
   equal(Object.keys(mascot.changedAttributes()).length, 0, 'after rollback attributes there are no changes');
 });
 
+test("changedAttributes() works while the record is being saved", function() {
+  var cat;
```
Comment (bmac) [inline packages/ember-data/tests/unit/model-test.js]: Since the assert is in an adapter method could you add `expect(1)` to the start of this test.

File: packages/ember-data/tests/unit/model-test.js [hunk 3]
```diff
@@ -298,6 +297,68 @@ test("changedAttributes() return correct values", function() {
...
+
+  run(function() {
+    cat = store.createRecord('mascot');
+    cat.setProperties({ name: 'Argon', likes: 'Cheese' });
+    cat.save();
+  });
+});
+
+test("changedAttributes() works while re record is being updated", function() {
+  var cat;
```
Comment (bmac) [inline packages/ember-data/tests/unit/model-test.js]: Also add `expect(1)` to this test.

**Comment by cibernox** [comment]
Updated

**Comment by bmac** [comment]
Looks good. :+1:

**Comment by cibernox** [comment]
Fixed a typo. Now it's done

**Comment by bmac** [comment]
Thanks @cibernox
