### PR TITLE
[BUGFIX BETA RELEASE] make fetch function JIT

### LINKED ISSUE #6326: cannot find the `fetch` module or the `fetch` global when using with fastboot
Howdy folks, it's me again 👋 

This issue is essentially the same problem as https://github.com/emberjs/data/issues/5998 but with a different error message so I thought I would create a new issue.

Essentially adding ember-cli-fastboot to a newly generated Ember app doesn't work and here is the error we get this time: 

```
Error: cannot find the `fetch` module or the `fetch` global. Did you mean to install the `ember-fetch` addon?
```

### Reproduction

Steps to reproduce:

- npm init ember-app test-app (npm init ember-app always makes sure it is up-to-date)
- cd test-app
- ember install ember-cli-fastboot
- npm start
- visit http://localhost:4200
- 💥

Here is a simple reproduction that has the issue https://github.com/mansona/ember-data-fetch-test but as you can see from the steps it's pretty easy to reproduce

### Versions

```cli
test-app@0.0.0 /Users/mansona/temp/test-app
└── ember-source@3.11.1

test-app@0.0.0 /Users/mansona/temp/test-app
└── ember-cli@3.11.0

test-app@0.0.0 /Users/mansona/temp/test-app
└── ember-data@3.11.4
```

/cc @rwjblue @runspired as we were looking at this together last time

### LINKED ISSUE #6380: ember-data@3.12 does not work in IE11
Steps to reproduce:
```
ember new test-ie
ember build --prod
```

When trying to browse in IE, the page will stay blank and throw:
```
SCRIPT5009: 'Symbol' is undefined
vendor.js (85124,5)
```

### PR DESCRIPTION
**Pull request by runspired**
resolves #6326 
resolves #6380

### CODE REVIEW

File: packages/adapter/addon/-private/utils/fetch.ts [hunk 1]
```diff
@@ -2,19 +2,23 @@ import require, { has } from 'require';
 
 type FetchFunction = (input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>;
 
-let _fetch: (() => FetchFunction) | null = null;
+let _fetch: FetchFunction | null = null;
```
Comment (rwjblue) [inline packages/adapter/addon/-private/utils/fetch.ts]: Actually, we can't cache this here. If we do, I believe that we break the ability for pretender to patch it.

Comment (runspired) [reply packages/adapter/addon/-private/utils/fetch.ts]: fixed
