### PR TITLE
WIP client-side-delete semantics `unloadRecord`

### LINKED ISSUE #5136: Loading a previously unloaded record doesn't update relationships
Unfortunately I've hit another unloadRecord bug. When I unload a record that is on the `belongsTo` side of a `one-to-many` it is correctly removed from the `hasMany` array. However when I push that same record back into the store, it is not added back to the `hasMany` array.

Ember: 2.14.1
Ember-Data: 2.14.10

Reproduction repo: [workmanw/unload-relationships-bug](https://github.com/workmanw/unload-relationships-bug). 
Code:  [app/controllers/index.js](https://github.com/workmanw/unload-relationships-bug/blob/master/app/controllers/index.js). 
Live example: https://workmanw.github.io/unload-relationships-bug
Failing Test: #5137

To reproduce:
1) Load Record
2) Unload Record
3) Load Record again.

You'll notice that the "All Comments" section shows the record was reloaded (re-pushed) into the store, however the relationship on the `post` is not updated to reflect this.

One note here, I'm using `async: false` on this relationship. If I use `async: true` it creates a crash on unload.

### PR DESCRIPTION
**Pull request by hjdivad**
Fix #5136, #5137

### CODE REVIEW

**Comment by hjdivad** [comment]
Follow-on for #5136 #5137

**Comment by hjdivad** [comment]
cc @igorT

File: tests/integration/records/unload-test.js [hunk 1]
```diff
@@ -1488,3 +1488,8 @@ test('many:many async unload', function (assert) {
     assert.equal(person1Friends.isDestroyed, true, 'previous ManyArray is destroyed in the runloop after refetching');
   });
 });
+
+test('1 sync : 1 async');
```
Comment (rwjblue) [inline tests/integration/records/unload-test.js]: Fwiw I do t think QUnit supports this syntax (assuming you are intending to basically create a skip?)...

Comment (hjdivad) [reply tests/integration/records/unload-test.js]: @rwjblue creating a todo, not a skip.

File: addon/-private/system/relationships/state/belongs-to.js [hunk 2]
```diff
@@ -15,6 +15,20 @@ export default class BelongsToRelationship extends Relationship {
...
 
+  _inverseIsAsync() {
+    if (!this.inverseKey || !this.inverseInternalModel) {
+      return false;
+    }
+    return this.inverseInternalModel._relationships.get(this.inverseKey).isAsync;
+  }
+
+  _inverseIsSync() {
+    if (!this.inverseKey || !this.inverseInternalModel) {
```
Comment (igorT) [inline addon/-private/system/relationships/state/belongs-to.js]: the model == null case should probably be handled by the caller?

File: addon/-private/system/relationships/state/has-many.js [hunk 3]
```diff
@@ -12,9 +12,17 @@ export default class ManyRelationship extends Relationship {
     this.canonicalState = [];
     this.isPolymorphic = relationshipMeta.options.polymorphic;
     this._manyArray = null;
+    this._retainedManyArray = null;
     this.__loadingPromise = null;
   }
 
+  _inverseIsAsync() {
```
Comment (igorT) [inline addon/-private/system/relationships/state/has-many.js]: This could live on the parent class

File: addon/-private/system/relationships/state/has-many.js [hunk 4]
```diff
@@ -44,6 +52,10 @@ export default class ManyRelationship extends Relationship {
         isPolymorphic: this.isPolymorphic
       });
     }
+    if (this._retainedManyArray !== null) {
```
Comment (igorT) [inline addon/-private/system/relationships/state/has-many.js]: Should this ever happen if manyArray is not null?

File: addon/-private/system/relationships/state/has-many.js [hunk 5]
```diff
@@ -78,10 +90,16 @@ export default class ManyRelationship extends Relationship {
...
-      this._manyArray = null;
+  inverseDidDematerialize(inverseInternalModel) {
+    if (this.isAsync) {
+      if (this._manyArray) {
+        this._retainedManyArray = this._manyArray;
+        this._manyArray = null;
+      }
+      this._removeInternalModelFromManyArray(this._retainedManyArray, inverseInternalModel);
+    } else {
+      this.removeInternalModelFromOwn(inverseInternalModel);
```
Comment (igorT) [inline addon/-private/system/relationships/state/has-many.js]: This seems to be common for both hasMany and belongsTo?

File: addon/-private/system/relationships/state/has-many.js [hunk 6]
```diff
@@ -143,7 +167,26 @@ export default class ManyRelationship extends Relationship {
       return;
     }
     super.removeInternalModelFromOwn(internalModel, idx);
-    let manyArray = this.manyArray;
+    // TODO: explain this madness
```
Comment (igorT) [inline addon/-private/system/relationships/state/has-many.js]: ❤️

File: addon/-private/system/relationships/state/relationship.js [hunk 7]
```diff
@@ -78,30 +78,27 @@ export default class Relationship {
     this.hasLoaded = false;
   }
 
-  get parentType() {
-    return this.internalModel.modelName;
+  _inverseIsAsync() {
+    // TODO: clean this up; it's for implicit relationships
+    return this.isAsync;
```
Comment (igorT) [inline addon/-private/system/relationships/state/relationship.js]: this seems incorrect?

File: addon/-private/system/relationships/state/has-many.js [hunk 8]
```diff
@@ -143,7 +167,26 @@ export default class ManyRelationship extends Relationship {
...
+    this._removeInternalModelFromManyArray(this.manyArray, internalModel, idx);
+    this._removeInternalModelFromManyArray(this._retainedManyArray, internalModel, idx);
```
Comment (igorT) [inline addon/-private/system/relationships/state/has-many.js]: we should maybe do this in the async case?

File: addon/-private/system/relationships/state/has-many.js (hunk 4 above)
Comment (igorT) [reply addon/-private/system/relationships/state/has-many.js]: lets add an assert

**Comment by fivetanley** [comment]
@hjdivad I tried this out in our app. We're still stuck in this scenario:

```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    unload() {
      const clients = this.store.peekAll('client');

      // there is one record that matches this, so one record unloaded
      clients.filterBy('isCool').forEach((client) => {
        client.unloadRecord();
      });
      
      // here clients is [Model, Model, null]
      // null should not be in the array
      
      // error here because filterBy calls Ember.get on null to try to find hasDirtyAttributes.
      clients.filterBy('hasDirtyAttributes').forEach(client => {
        client.unloadRecord();
      });
    }
  }
});
```

It looks like some `null`s are still getting stuck in the RecordArray created for `this.store.peekAll('client')`.

**Comment by hjdivad** [comment]
Thanks for the followup @fivetanley.  I'll see about reproducing this in a test if you haven't already.

File: addon/-private/system/relationships/state/has-many.js (hunk 8 above)
Comment (hjdivad) [reply addon/-private/system/relationships/state/has-many.js]: we discussed this OOB, but LMK if you still think there's an issue here

**Comment by hjdivad** [comment]
@igorT this should be good to merge; issues we discussed are handled.

**Comment by hjdivad** [comment]
@fivetanley this doesn't resolve the filter issue you mentioned [in your previous comment](https://github.com/emberjs/data/pull/5273#issuecomment-356679354); that will be addressed in a follow-on issue.

**Comment by sly7-7** [comment]
@fivetanley I wonder if in your use case, calling toArray() after filter would change anything ?

**Comment by workmanw** [comment]
This isn't tagged with the release channel. Can we please get this in 2.18 LTS?

**Comment by workmanw** [comment]
Shameless bump @hjdivad @rwjblue -- Can we get this PR and #5249 into 2.18.1? I know DS doesn't have the same level LTS support as Ember, but it would be nice to have a place to jump to in the 2.x series.

**Comment by sly7-7** [comment]
Or at least in 3.0 beta ?

**Comment by elgordino** [comment]
FYI This is included in 3.1.0-beta.1 https://github.com/emberjs/data/releases

**Comment by bmac** [comment]
I just released 2.18.1 and 3.0.1 with this pr. Thanks to @sly7-7 for pinging me about including this pr.

**Comment by workmanw** [comment]
@bmac Thank you!!

**Comment by jlami** [comment]
@hjdivad What is the status of the followup on the problem @fivetanley was having?
I think this might be the same problem as I'm having. see also #5353 and #5354 

Could somebody explain the reasoning behind the distinction in handling of the canonical state of sync and async relationships for unload? I'm inclined the client side should not be effected by this, as this is more of a server behaviour in my mind.
