### PR TITLE
[BUGFIX] AMS polymorphic type for namespaced models

### LINKED ISSUE #3019: ActiveModelSerializer: wrong polymorphic type processing for namespaced model name
With `docs/invoice` model in Ember that corresponds to `Docs::Invoice` rails model:
- ember sends to server unexpected `"Docs/invoice"` as polymorphic type, instead of `"Docs::Invoice"`
````javascript
comment: { target_id: "1", target_type: "Docs/invoice", ... }
// expected target_type: "Docs::Invoice"
````
- from server payload ember doesn't accept `type: "Docs::Invoice"` as model name, but accepts `type: "docs/invoice"` .
````javascript
   account: {..., docs:[{ id: "1", type: "Docs::Invoice" }, ... ]} 
  // unexpected error "No model was found for 'docs::Invoice'"
  // expected extracting as 'docs/invoice' model 
`````
 
Details. 
Let `Docs::Invoice`, `Comment`, `Account` rails model names, 
in Ember-cli 0.2.3 (Ember-data 1.0.0-beta.16.1) 
````javascript
// models/comment.js
export default DS.Model.extend({
  // ...
  target: DS.belongsTo('doc', { async: true, polymorphic: true, inverse: 'comments' })
});

// models/doc.js
export default DS.Model.extend({
  // ...
  comments: DS.hasMany('comment', { async: true, inverse: 'target' }),
  account: DS.belongsTo('account', { async:true, inverse:'docs' });
});
// models/docs/invoice.js
export default DocModel.extend({
  // ...
});
// models/account
export default DS.Model.extend({
  // ...
  docs: DS.hasMany('docs', { polymorphic: true, async: true, inverse: 'account' });
});
````

So after:
````javascript
   this.store.createRecord('comment', {target: target, ... }).save();
````
the `comment` payload to server has unexpected `target_type`:
````javascript
comment: {
   target_id: "1",
   target_type: "Docs/invoice"
   ... }
// expected target_type: "Docs::Invoice"
````

After 
````javascript
  this.store.find('account', 1);
````
and processing payload from server
````javascript
account: {..., docs:[{id:"1", type:"Docs::Invoice"}, ... ]}
// serializer extracts docs as 'docs::Invoice' model and raises "not found model" error, 
// but should extract docs as 'docs/invoice' model
````
error raises: `Error: No model was found for 'docs::Invoice'`. 
So I have to patch server output to provide underscored type: 
`account: {..., docs:[{id:"1", type:"docs/invoice"}, ... ]} ` and then it works.

### PR DESCRIPTION
**Pull request by artych**
Tests and patch fixes #3019

### CODE REVIEW

**Comment by artych** [comment]
I am not sure about typeForRoot function: should it be patched in RESTSerializer or be rewritten in AMS. I decided to rewrite it in AMS since fixed behavior is rails (or ruby) specific.

File: packages/activemodel-adapter/lib/system/active-model-serializer.js [hunk 1]
```diff
@@ -285,7 +288,17 @@ var ActiveModelSerializer = RESTSerializer.extend({
         }
       }, this);
     }
+  },
+
+  typeForRoot: function(key) {
+
```
Comment (igorT) [inline packages/activemodel-adapter/lib/system/active-model-serializer.js]: Extra whitespace here

**Comment by igorT** [comment]
I think this looks good.

File: packages/activemodel-adapter/lib/system/active-model-serializer.js [hunk 2]
```diff
@@ -166,7 +166,10 @@ var ActiveModelSerializer = RESTSerializer.extend({
     if (Ember.isNone(belongsTo)) {
       json[jsonKey] = null;
     } else {
-      json[jsonKey] = capitalize(camelize(belongsTo.typeKey));
+      json[jsonKey] = belongsTo.typeKey.split("/").map(function(part) {
```
Comment (fivetanley) [inline packages/activemodel-adapter/lib/system/active-model-serializer.js]: We can't use map here due to IE8 support (I'm not sure when we're dropping it). You can use Ember.EnumerableUtils.map instead.

File: packages/activemodel-adapter/lib/system/active-model-serializer.js [hunk 3]
```diff
@@ -285,6 +288,12 @@ var ActiveModelSerializer = RESTSerializer.extend({
         }
       }, this);
     }
+  },
+  typeForRoot: function(key) {
+    return singularize(key)
+      .split('::').map(function(part) {
```
Comment (fivetanley) [inline packages/activemodel-adapter/lib/system/active-model-serializer.js]: same here

**Comment by fivetanley** [comment]
This also looks good to me but I think we should call this out in CHANGELOG.md and the release blog post. Can you add an entry to the CHANGELOG ?

**Comment by artych** [comment]
In fact there is no need for `map` in both cases, it's enough to use `replace("::","/")` and  (`classify <-> underscore` conversion. But now `classify` doesn't work properly (my opinion):
````javascript
  Ember.String.classify("evilMinions/yellowMinion");
//=> "EvilMinions/yellowMinion"
//=> expected  "EvilMinions/YellowMinion"
````
Do you agree?

**Comment by artych** [comment]
@fivetanley you mean add bullet line to CHANGELOG for 1.0.0-beta.17 version?

**Comment by fivetanley** [comment]
Looks like you already added an issue to Ember Inflector. Looks like a bug to me and @stefanpenner https://github.com/stefanpenner/ember-inflector/issues/77

**Comment by artych** [comment]
Ok, I thought inflector is only about singularize and pluralize.

**Comment by artych** [comment]
@fivetanley CHANGELOG entry added. Is it good now or I should do something more?
And look at  emberjs/emberjs#10980, please, that fixes string conversions pug mentioned in comments before (since corresponding ember/inflector issue is closed today).

**Comment by artych** [comment]
Ember.String issue is moved in ember.js repo just to make this conversation clear.

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,8 @@
 
 ### Master
 
+ * Fix ActiveModelSerializer serializePolymorphicType and typeForRoot methods for properly serializing and extracting namespaced model names in polymorphic type attributes.
```
Comment (igorT) [inline CHANGELOG.md]: Can you mention the issue name, and also just quickly say it's now accepting `::` instead of `/`

**Comment by igorT** [comment]
Looks, good can you just cleanup the changelog a bit, and I'll merge asap
Thanks!

**Comment by artych** [comment]
Thank you, @igorT. Changelog entry is changed, this patch should be simplified after fixing  emberjs/ember.js#11000.
I am glad to make a small contribution to Ember, please, contact me if I can do anything more.

File: packages/activemodel-adapter/lib/system/active-model-serializer.js [hunk 5]
```diff
@@ -166,7 +166,9 @@ var ActiveModelSerializer = RESTSerializer.extend({
     if (Ember.isNone(belongsTo)) {
       json[jsonKey] = null;
     } else {
-      json[jsonKey] = capitalize(camelize(belongsTo.typeKey));
+      json[jsonKey] = classify(belongsTo.typeKey).replace(/(\/)([a-z])/g, function(match, separator, chr) {
```
Comment (fivetanley) [inline packages/activemodel-adapter/lib/system/active-model-serializer.js]: Perhaps this could be rewritten as `classify(belongsTo.typeKey).split('/').map(classify).join('::')` ?

Comment (fivetanley) [inline packages/activemodel-adapter/lib/system/active-model-serializer.js]: Seems fine to me overall though.
