### PR TITLE
[REGRESSION release] Make meta available with new Serializer API

### LINKED ISSUE #3391: Metadata lost in RESTAdapter with isNewSerializerAPI
I talked with @wecc a bit about this in Slack, and it looks like metadata is extracted but not saved when the `RESTAdapter` has its `isNewSerializerAPI` set to true. Here is an example of the problem: 

http://emberjs.jsbin.com/moxuno/3/edit?html,js,output

You can see it not working or working by setting the `isNewSerializerAPI` attribute on the `ApplicationSerializer`.

### PR DESCRIPTION
**Pull request by wecc**
We forgot to deprecate `store.metadataFor` and `store.setMetadataFor` when releasing 1.13. We also failed to keep backwards compatibility with metadata for users that are preparing for 2.0 and switches over to the new Serializer API.

This PR fixes that regression and correctly deprecates `store.metadataFor` and `store.setMetadataFor`.

Fixes #3391

### CODE REVIEW

File: packages/ember-data/lib/system/store.js [hunk 1]
```diff
@@ -1388,8 +1388,20 @@ Store = Service.extend({
     @method metadataFor
     @param {String} modelName
     @return {object}
+    @deprecated
   */
   metadataFor: function(modelName) {
+    Ember.deprecate("`store.metadataFor()` has been deprecated. You can use `.get('meta')` on relationships and arrays returned from `store.query()`.");
+    return this._metadataFor(...arguments);
```
Comment (igorT) [inline packages/ember-data/lib/system/store.js]: can just do modelName

File: packages/ember-data/lib/system/store.js [hunk 2]
```diff
@@ -1402,8 +1414,20 @@ Store = Service.extend({
     @param {String} modelName
     @param {Object} metadata metadata to set
     @return {object}
+    @deprecated
   */
   setMetadataFor: function(modelName, metadata) {
+    Ember.deprecate("`store.setMetadataFor()` has been deprecated. Please return meta from your serializer's `extractMeta` hook.");
+    this._setMetadataFor(...arguments);
```
Comment (igorT) [inline packages/ember-data/lib/system/store.js]: same here

**Comment by JKGisMe** [comment]
if it's being deprecated, what's the new way?

**Comment by wecc** [comment]
@JKGisMe You can get meta off of relationships plus arrays returned from `query` by doing `.get('meta')` (when this has been released).

**Comment by kottenator** [comment]
What about "meta" on the top level (not inside relationships)? What is the correct replacement of `this.store.metadataFor('smth')`?

I've provided the full example/question in [another ticket](https://github.com/emberjs/data/issues/3419)
