### PR TITLE
Warnings for incorrect options in belongsTo, resolves #3187

### LINKED ISSUE #3187: If someone passes serialize:true or embedded:true to the relationship helper, warn them it's not the right place
If someone does something like
```
var User = DS.Model({
   friend: DS.belongsTo('friends', { serialize: true })
})
```
we should warn them

### PR DESCRIPTION
**Pull request by zoeesilcock**
Display a warning when the user specifies ```serialize``` or ```embedded``` in the options for ```belongsTo```. These settings belong in the serializer now, I have linked to the relevant documentation pages in order to help the user to do what they meant to do. Resolves #3187.

### CODE REVIEW

File: packages/ember-data/lib/system/relationships/belongs-to.js [hunk 1]
```diff
@@ -93,6 +93,14 @@ function belongsTo(modelName, options) {
 
   opts = opts || {};
 
+  if (opts.hasOwnProperty('serialize')) {
+    Ember.warn('You provided a serialize option, this belongs in the serializer. See DS.Serializer and it\'s implementations http://emberjs.com/api/data/classes/DS.Serializer.html');
```
Comment (igorT) [inline packages/ember-data/lib/system/relationships/belongs-to.js]: Can you tell the user for which model they provided it, that would make the warning much less confusing. Something like: In the `modelName` class,  passed a serialize option to the belongsTo relationship `key`. You most likely want to be configuring that in the serializer...

Comment (zoeesilcock) [inline packages/ember-data/lib/system/relationships/belongs-to.js]: Good idea, I'll change the error message.

Comment (zoeesilcock) [inline packages/ember-data/lib/system/relationships/belongs-to.js]: Sorry @igorT, I can't figure out how to provide the information you mentioned. I can only get ahold of the ```modelName``` which is the name of the model that the relationship is to. I can't find the name of the model or the property on where the ```belongsTo``` was used.

Comment (igorT) [inline packages/ember-data/lib/system/relationships/belongs-to.js]: If you move the warning into the getter, you should be able to do this. Perf isn't as important as anything inside Ember.warn/assert etc. gets stripped in production

File: packages/ember-data/lib/system/relationships/belongs-to.js [hunk 2]
```diff
@@ -102,6 +102,14 @@ function belongsTo(modelName, options) {
 
   return computedPolyfill({
     get: function(key) {
+      if (opts.hasOwnProperty('serialize')) {
```
Comment (igorT) [inline packages/ember-data/lib/system/relationships/belongs-to.js]: Can you put the `opts.hasOwnProperty('serialize')` inside the warn, so it will get stripped in production?
