### PR TITLE
Fix: a record in state deleted.invalid can be rollbacked

### LINKED ISSUE #2126: Invalid state for root.deleted
Apparently Ember does not allow me to invalidate a DELETE request.

If my ```App.model.destroyRecord()``` returns a default ```Errors object``` with the message 'Deletion is not allowed', embers raises a 

```
Attempted to handle event `becameInvalid` on <App.Model:ember718:2> while in state root.deleted.inFlight
```

Since its not the object error itself, I can't retrieve the error message.

But... If I try to delete again, then I get the right error response from the server with the error messages returned.

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.7.0-beta.3
DEBUG: Ember Data : 1.0.0-beta.8.2a68c63a
DEBUG: Handlebars : 1.3.0
DEBUG: jQuery     : 1.11.1
DEBUG: -------------------------------
```

### PR DESCRIPTION
**Pull request by ppcano**
Fix #2126, #2169, #2708 

Defines the `root.deleted.invalid` state and its different events. 

Now  a record which has been invalidated during its `deletion` can be rollbacked on the same way that if it would receive an error response.

### CODE REVIEW

File: packages/ember-data/lib/system/model/states.js [hunk 1]
```diff
@@ -658,6 +658,11 @@ var RootState = {
       becameError: function(record) {
         record.transitionTo('uncommitted');
         record.triggerLater('becameError', record);
+      },
+
+      becameInvalid: function(record) {
+        record.transitionTo('invalid');
+        record.triggerLater('becameInvalid', record);
```
Comment (bmac) [inline packages/ember-data/lib/system/model/states.js]: Why do we run `triggerLater` here?

Comment (ppcano) [inline packages/ember-data/lib/system/model/states.js]: I thought, it needed to be called because `DirtyState.inFlight.becameInvalid` calls `record.send('invokeLifecycleCallbacks')` and then:
```js
invalid: {
    invokeLifecycleCallbacks: function(record) {
      record.triggerLater('becameInvalid', record);
    }
}
```

The implementation is based on other `invalid event` implementations but honestly, I didn't understand well when `record.triggerLater('becameInvalid', record);` is necessary.

If I removed this `triggerLater`, the test pass. Do you want to me to update PR?

**Comment by tomdale** [comment]
@ppcano Does this supersede #2169? If we take this PR, do we not need to take the other?

**Comment by ppcano** [comment]
@tomdale yes, this one supersede #2169

**Comment by jcope2013** [comment]
any timeline on this landing soon?

**Comment by bmac** [comment]
Thanks

**Comment by atomkirk** [comment]
Isn't the better approach to include the `DirtyState` in the deleted state? Per the docs:
>The dirty state is a abstract state whose functionality is
>shared between the `created` and `updated` states.
