### PR TITLE
Silence warnings and deprecations in the console during tests

### LINKED ISSUE #4416: Running tests shows Warnings and Deprecation's
When i run the tests i get warnings and deprecation's.

Before i try to see if i can get rid of them i want to understand if this is expected behavior, or am i doing something wrong ?
- WARNING: FEATURE["ds-serialize-ids-and-types"] is set as enabled, but FEATURE flags are only available in canary builds.
- DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or `import DS from 'ember-data';`. [deprecation id: ember-data.global-ds]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at get (http://localhost:4200/assets/vendor.js:82215:44)
      at http://localhost:4200/assets/tests.js:21:21
- DEPRECATION: The adapter returned an array for the primary data of a `queryRecord` response. This is deprecated as `queryRecord` should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at http://localhost:4200/assets/vendor.js:85334:48
      at runInDebug (http://localhost:4200/assets/vendor.js:16645:5)
- WARNING: Interacting with a record errors object will no longer change the record state.
- WARNING: There is no attribute or relationship with the name `notInMapping` on `post`. Check your serializers attrs hash.
- DEPRECATION: `RESTSerializer.normalizeHash` has been deprecated. Please use `serializer.normalize` to modify the payload of single resources. [deprecation id: ds.serializer.normalize-hash-deprecated]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at normalize (http://localhost:4200/assets/vendor.js:85181:46)
      at superWrapper [as normalize](http://localhost:4200/assets/vendor.js:33225:22)
- WARNING: Ember Data expected to find records with the following ids in the adapter response but they were missing: [igor]

### PR DESCRIPTION
**Pull request by bmac**
Closes #4416 

#### Before
screen shot 2016-11-17 at 10 04 57 am
screen shot 2016-11-17 at 10 05 05 am

#### After
screen shot 2016-11-17 at 9 57 12 am

### CODE REVIEW

**Comment by stefanpenner** [comment]
just checking but this doesn't only silence them, but asserts they do or do not happen & happens to silence them right?

File: tests/integration/serializers/json-serializer-test.js [hunk 1]
```diff
@@ -987,9 +987,10 @@ test('normalizeResponse ignores unmapped attributes', function(assert) {
     title: "Rails is omakase"
   };
 
-  var post = env.store.serializerFor("post").normalizeResponse(env.store, Post, jsonHash, '1', 'findRecord');
-
-  assert.equal(post.data.attributes.title, "Rails is omakase");
+  assert.expectWarning(function() {
```
Comment (pangratz) [inline tests/integration/serializers/json-serializer-test.js]: Since this tests adds an assertion for an expected warning, you need to use `testInDebug` instead of `test`, since otherwise this test will fail when the ember data tests are run in the production build.

File: tests/unit/store/adapter-interop-test.js [hunk 2]
```diff
@@ -836,7 +836,7 @@ test("the promise returned by `_scheduleFetch`, when it rejects, does not depend
 });
 
 test("store._fetchRecord reject records that were not found, even when those requests were coalesced with records that were found", function(assert) {
```
Comment (pangratz) [inline tests/unit/store/adapter-interop-test.js]: see above: `s/test/testInDebug`

**Comment by bmac** [comment]
> just checking but this doesn't only silence them, but asserts they do or do not happen & happens to silence them right?

I added 2 assertions that happens to silence the warnings mainly for the side effect of silencing the warnings. The json-serializer-test.js did not have an existing test for the warning, however the adapter-interop-test [does have an explicit test for the warning](https://github.com/bmac/data/blob/dcea34116972fb349842b7777433186a96a28583/tests/unit/store/adapter-interop-test.js#L878) which my change now duplicates.

For the since almost all of the tests in the errors object trigger a warning I overrode [Ember.warn for that entire module](https://github.com/emberjs/data/pull/4663/files#diff-365a2631b698bbbb4a84586bf51c7d7d).

I also added an ignoreDeprecation in the rest-adapter-test.js which doesn't and any assertions since there [is already a test for that deprecation](https://github.com/bmac/data/blob/dcea34116972fb349842b7777433186a96a28583/tests/integration/adapter/rest-adapter-test.js#L1369-L1383)

**Comment by stefanpenner** [comment]
Although a pain, I think the ideal is. error on unexpected warn, error on unexpected deprecation. And require assertions in those places.

Maybe there is a middleground, but hiding warning/deprecations is a slippery slope.

**Comment by pangratz** [comment]
We had this once (added in #3834) but somehow this isn't working anymore. At least not the last time I checked (if I remember correctly).

**Comment by pangratz** [comment]
I see that there has been some work in #3995.

@bmac do you want to investigate if [this](https://github.com/emberjs/data/blob/7a12c44a5631cbef8ed2f30fe10f1df7b2b6c14b/tests/dummy/config/environment.js#L20-L22) might be working now?

**Comment by bmac** [comment]
I have updated this pr to explicitly tests for all of the deprecations and warnings that were ignored in the earlier version of this pr.

@pangratz enabling that flag now causes the build to fail when there is a deprecation warning.

File: tests/helpers/setup-ember-dev.js [hunk 3]
```diff
@@ -2,7 +2,7 @@
 import Ember from 'ember';
 import EmberTestHelpers from "ember-dev/test-helper/index";
 
-const AVAILABLE_ASSERTIONS = ['expectAssertion', 'expectDeprecation', 'expectNoDeprecation', 'expectWarning', 'expectNoWarning'];
+const AVAILABLE_ASSERTIONS = ['expectAssertion', 'expectDeprecation', 'expectNoDeprecation', 'expectWarning', 'expectNoWarning', 'ignoreDeprecation'];
```
Comment (pangratz) [inline tests/helpers/setup-ember-dev.js]: Seems like `ignoreDeprecation` is not used?

**Comment by pangratz** [comment]
Thanks for your work in this @bmac!! 🚀
