### PR TITLE
backport fix for clearing subscriptions from #8116 (fix #7857)

### LINKED ISSUE #7857: BelongsTo-Relation changes throw error in Store -> unsubscribe
Hi there,

i have a existing model with attributes and relationships. For example this model has a existent belongsTo relationship named "gender". 

When i set this belongsTo to null, all good at the moment, i get no error.

And if I now but change this nullified belongsTo to another relation, i get a error from stores record-notification-manager like "Passed unknown unsubscribe token to unsubscribe". 

If i change this belongsTo directly to a new relation, i get no error.

In the case that I have loaded an existing model where the belongsTo "gender" is null and I set to a relation, I don't get an error.

This is a bug that I don't think appeared before ember 4. I think the problem comes with this change https://github.com/emberjs/data/commit/856f7b33ab60b9327839fe80b7ae3588e863f657.

I use:
ember-cli 4.1.1
ember-source 4.1.0
ember-data 4.1.0

### PR DESCRIPTION
**Pull request by runspired**

### CODE REVIEW

File: packages/store/addon/-private/system/references/has-many.ts [hunk 1]
```diff
@@ -76,6 +76,7 @@ export default class HasManyReference extends Reference {
   destroy() {
     if (CUSTOM_MODEL_CLASS) {
       unsubscribe(this.#token);
+      this.#token = null as unknown as object;
```
Comment (jherdman) [inline packages/store/addon/-private/system/references/has-many.ts:79]: This is a bit out of band, but tell me more about this double `as`.

Comment (runspired) [reply packages/store/addon/-private/system/references/has-many.ts:79]: if something already has a type, you can't recast it without first casting to unknown

**Comment by runspired** [comment]
The LTS scenario failures appears to be a CI only issue and unrelated to this change
